import { createTheme } from '@fluentui/react';

export const themes = {
  light: createTheme({
    palette: {
      themePrimary: '#0078d4',
      themeLighterAlt: '#f3f9fd',
      themeLighter: '#d0e7f8',
      themeLight: '#a9d3f2',
      themeTertiary: '#5ca9e5',
      themeSecondary: '#1a86d9',
      themeDarkAlt: '#006cbe',
      themeDark: '#005ba1',
      themeDarker: '#004377',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  }),
  dark: createTheme({
    palette: {
      themePrimary: '#2899f5',
      themeLighterAlt: '#010509',
      themeLighter: '#051625',
      themeLight: '#092a45',
      themeTertiary: '#12548a',
      themeSecondary: '#1a7bca',
      themeDarkAlt: '#3ea3f6',
      themeDark: '#5cb2f7',
      themeDarker: '#88c6f9',
      neutralLighterAlt: '#2b2b2b',
      neutralLighter: '#333333',
      neutralLight: '#414141',
      neutralQuaternaryAlt: '#4a4a4a',
      neutralQuaternary: '#515151',
      neutralTertiaryAlt: '#6f6f6f',
      neutralTertiary: '#c8c8c8',
      neutralSecondary: '#d0d0d0',
      neutralPrimaryAlt: '#dadada',
      neutralPrimary: '#ffffff',
      neutralDark: '#f4f4f4',
      black: '#f8f8f8',
      white: '#222222',
    },
  }),
  nature: createTheme({
    palette: {
      themePrimary: '#2d8a63',
      themeLighterAlt: '#f2f9f6',
      themeLighter: '#d1e9df',
      themeLight: '#afd7c5',
      themeTertiary: '#6ab394',
      themeSecondary: '#3d9470',
      themeDarkAlt: '#297c59',
      themeDark: '#22694b',
      themeDarker: '#194e38',
      neutralLighterAlt: '#f7f7f5',
      neutralLighter: '#f0f0ec',
      neutralLight: '#e2e2da',
      neutralQuaternaryAlt: '#d2d2c8',
      neutralQuaternary: '#c6c6ba',
      neutralTertiaryAlt: '#bcbcb0',
      neutralTertiary: '#999988',
      neutralSecondary: '#666655',
      neutralPrimaryAlt: '#4f4f40',
      neutralPrimary: '#333322',
      neutralDark: '#2b2b1c',
      black: '#222216',
      white: '#fffffe',
    },
  }),
  sunset: createTheme({
    palette: {
      themePrimary: '#d83b01',
      themeLighterAlt: '#fdf5f0',
      themeLighter: '#f8d6c8',
      themeLight: '#f3b69f',
      themeTertiary: '#e77c4e',
      themeSecondary: '#dd4b12',
      themeDarkAlt: '#c43501',
      themeDark: '#a62d01',
      themeDarker: '#7a2101',
      neutralLighterAlt: '#fff4ee',
      neutralLighter: '#ffeadd',
      neutralLight: '#ffd6c0',
      neutralQuaternaryAlt: '#ffc9ab',
      neutralQuaternary: '#ffbe9c',
      neutralTertiaryAlt: '#ffb48d',
      neutralTertiary: '#cca68a',
      neutralSecondary: '#a9785f',
      neutralPrimaryAlt: '#865642',
      neutralPrimary: '#764231',
      neutralDark: '#633829',
      black: '#4e2c20',
      white: '#fff9f5',
    },
  }),
};
